"""create housing records table

Revision ID: da3c0389a266
Revises: 
Create Date: 2026-06-16 11:43:17.459228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3c0389a266'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_records',
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('region_type', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('average_sale_price', sa.Integer(), nullable=True),
    sa.Column('price_index', sa.Float(), nullable=True),
    sa.Column('total_sold', sa.Integer(), nullable=True),
    sa.Column('year_over_year_change', sa.Float(), nullable=True),
    sa.Column('total_value_sold', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'region_code', 'year', 'month', 'period_type', name='uq_country_region_period')
    )
    op.create_index(op.f('ix_housing_records_country'), 'housing_records', ['country'], unique=False)
    op.create_index(op.f('ix_housing_records_id'), 'housing_records', ['id'], unique=False)
    op.create_index(op.f('ix_housing_records_region'), 'housing_records', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_housing_records_region'), table_name='housing_records')
    op.drop_index(op.f('ix_housing_records_id'), table_name='housing_records')
    op.drop_index(op.f('ix_housing_records_country'), table_name='housing_records')
    op.drop_table('housing_records')
    # ### end Alembic commands ###
